init:
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

test_script:
- sh: ROOTFILES="$(find $HOME -user root)"
- sh: if [[ -n "$ROOTFILES" ]]; then echo "found root owned files!"; echo -n "$ROOTFILES"; echo; return 1; fi

build: off
